services:
  - type: web
    name: emotion-cipher
    runtime: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install --no-cache-dir -r requirements.txt
      # Install CPU version of Torch
      pip install --no-cache-dir --index-url https://download.pytorch.org/whl/cpu torch
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: TRANSFORMERS_CACHE
        value: "/opt/render/project/.cache/huggingface"
